### ISSUE TITLE
mensaje de warning en produccion analizar si se puede evitar y que es

### ISSUE THREAD

**Issue by alevilar** [alevilar/paxabot-nodejs#6]
Enviando mensaje por telegram
Mensaje enviado
(node:4503) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: chat not found
    at Telegram.callApi (/home/alevilar/wspaxapos/node_modules/telegraf/lib/core/network/client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4503) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
CONNECTED: ::ffff:127.0.0.1:48516
Enviando mensaje por telegram
Mensaje enviado
(node:4503) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: chat not found
    at Telegram.callApi (/home/alevilar/wspaxapos/node_modules/telegraf/lib/core/network/client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
CONNECTED: ::ffff:127.0.0.1:48518
Enviando mensaje por telegram
Mensaje enviado
(node:4503) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: chat not found
    at Telegram.callApi (/home/alevilar/wspaxapos/node_modules/telegraf/lib/core/network/client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by nicopenaloza** [comment]
Bot ya no corta cuando hay un error al enviar mensaje, Ahora te notifica del error pero continua funcionando.

`
Mensaje a 1313336088 no se pudo enviar 
Error:  TelegramError: 400: Bad Request: chat not found
    at Telegram.callApi (D:\test_paxabot\node_modules\telegraf\lib\core\network\client.js:258:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: chat not found'
  },
  on: {
    method: 'sendMessage',
    payload: { chat_id: 1313336088, text: 'TEST' }
  }
}
`

Ese es un mensaje de error de los que manda el bot
